name: tattoos
description: "Tattoos Hamburg"

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  cached_network_image: ^3.4.1
  country_flags: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  font_awesome_flutter: ^10.7.0
  get: ^5.0.0-release-candidate-9
  go_router: ^14.2.3
  google_maps_flutter: ^2.3.0
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0
  seo_renderer: ^0.6.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  url_strategy: ^0.3.0
  video_player: ^2.9.1
  whatsapp_unilink: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.5

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  fonts:
    - family: MPlus
      fonts:
        - asset: google_fonts/MPLUSRounded1c-Thin.ttf
          weight: 100
          style: normal
        - asset: google_fonts/MPLUSRounded1c-Light.ttf
          weight: 200
          style: normal
        - asset: google_fonts/MPLUSRounded1c-Regular.ttf
          weight: 300
          style: normal
        - asset: google_fonts/MPLUSRounded1c-Medium.ttf
          weight: 400
          style: normal
        - asset: google_fonts/MPLUSRounded1c-Bold.ttf
          weight: 500
          style: normal
        - asset: google_fonts/MPLUSRounded1c-ExtraBold.ttf
          weight: 600
          style: normal
        - asset: google_fonts/MPLUSRounded1c-Black.ttf
          weight: 700
          style: normal

  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/map_style/

flutter_intl:
  enabled: true
  main_locale: de